### ISSUE TITLE
test installation failed 

### ISSUE THREAD

**Issue by irmathebest** [riscv-software-src/homebrew-riscv#79]
Hi all. I am wondering, have anyone encountered this error when testing the installation of the riscv-gnu-toolchain? I used MacBook M1 with bigSur 11.4. Thanks. 
<img width="1205" alt="Screen Shot 2021-12-26 at 11 09 26 PM" src="https://user-images.githubusercontent.com/96667825/147433565-c05a750e-0e12-40bb-97db-733434e75eb4.png">

**Comment by sbeamer** [comment]
Should be fixed now (might need to rebuild). Probably a regression from #71.

**Comment by irmathebest** [comment]
> Should be fixed now (might need to rebuild). Probably a regression from #71.

Thank you so much for your help. However, I rebuild it with the command " brew reinstall --build-from-source riscv-gnu-toolchain", but the error still exists when I test it.

**Comment by sreersr** [comment]
> Hi all. I am wondering, have anyone encountered this error when testing the installation of the riscv-gnu-toolchain? I used MacBook M1 with bigSur 11.4. Thanks.
> <img alt="Screen Shot 2021-12-26 at 11 09 26 PM" width="1205" src="https://user-images.githubusercontent.com/96667825/147433565-c05a750e-0e12-40bb-97db-733434e75eb4.png">

Hi I have same issue can you help me to fix this

**Comment by sbeamer** [comment]
To clarify, you will need to rebuild spike (riscv-isa-sim) and riscv-pk, but you shouldn't need to rebuild riscv-gnu-toolchain.

The error was actually quite small. The compiler and emulator both worked fine. The issue was the emulator's hard coded path to check for pk was wrong, but fi you gave the full path to pk it would work. If you aren't using pk or spike, none of this would matter.

**Comment by sreersr** [comment]
Hi Scott,
Thanks and I had fixed with your advise. I also need a guidance how to run a simple c code in this setup, since risk tool chain is installed using a home-brew I am not sure how to run it, please advise thanks in advance. Also do I get a RTL code for the RISCV core used here?.

**Comment by sreersr** [comment]
I was trying to use RISCV toolchain with the Ariane core from https://github.com/openhwgroup/cva6 and trying to build it, but while running make Verilate the following error is observed, please advise. it will be appreciated if you give separate advise for my queries. Thanks in advance. 
<img width="1440" alt="Screen Shot 2022-01-01 at 7 55 50 AM" src="https://user-images.githubusercontent.com/83933455/147851197-4c643d4c-fb7b-46a0-909b-4dfa2a231520.png">

**Comment by sbeamer** [comment]
This repo is specifically for assisting with getting a vanilla installation of the RISC-V toolchain on macOS.

It does not provide processor RTL. For questions about a given implementation, I would follow up with the provider.

For running a simple program, you can follow the instructions from the simulator: https://github.com/riscv-software-src/riscv-isa-sim#compiling-and-running-a-simple-c-program
